# Generated by Django 5.0.3 on 2024-04-30 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shoppingcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='products',
            new_name='product',
        ),
    ]
